/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for BillOfMaterialResponse type.
 */
public class BillOfMaterialResponse {
    private List<BillOfMaterialsInformation> billsOfMaterials;

    /**
     * Default constructor.
     */
    public BillOfMaterialResponse() {
    }

    /**
     * Initialization constructor.
     * @param  billsOfMaterials  List of BillOfMaterialsInformation value for billsOfMaterials.
     */
    public BillOfMaterialResponse(
            List<BillOfMaterialsInformation> billsOfMaterials) {
        this.billsOfMaterials = billsOfMaterials;
    }

    /**
     * Getter for BillsOfMaterials.
     * @return Returns the List of BillOfMaterialsInformation
     */
    @JsonGetter("billsOfMaterials")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<BillOfMaterialsInformation> getBillsOfMaterials() {
        return billsOfMaterials;
    }

    /**
     * Setter for BillsOfMaterials.
     * @param billsOfMaterials Value for List of BillOfMaterialsInformation
     */
    @JsonSetter("billsOfMaterials")
    public void setBillsOfMaterials(List<BillOfMaterialsInformation> billsOfMaterials) {
        this.billsOfMaterials = billsOfMaterials;
    }

    /**
     * Converts this BillOfMaterialResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BillOfMaterialResponse [" + "billsOfMaterials=" + billsOfMaterials + "]";
    }

    /**
     * Builds a new {@link BillOfMaterialResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BillOfMaterialResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .billsOfMaterials(getBillsOfMaterials());
        return builder;
    }

    /**
     * Class to build instances of {@link BillOfMaterialResponse}.
     */
    public static class Builder {
        private List<BillOfMaterialsInformation> billsOfMaterials;



        /**
         * Setter for billsOfMaterials.
         * @param  billsOfMaterials  List of BillOfMaterialsInformation value for billsOfMaterials.
         * @return Builder
         */
        public Builder billsOfMaterials(List<BillOfMaterialsInformation> billsOfMaterials) {
            this.billsOfMaterials = billsOfMaterials;
            return this;
        }

        /**
         * Builds a new {@link BillOfMaterialResponse} object using the set fields.
         * @return {@link BillOfMaterialResponse}
         */
        public BillOfMaterialResponse build() {
            return new BillOfMaterialResponse(billsOfMaterials);
        }
    }
}
