/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for BillOfMaterialsInformation type.
 */
public class BillOfMaterialsInformation {
    private String name;
    private String version;
    private List<Chart> charts;

    /**
     * Default constructor.
     */
    public BillOfMaterialsInformation() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  version  String value for version.
     * @param  charts  List of Chart value for charts.
     */
    public BillOfMaterialsInformation(
            String name,
            String version,
            List<Chart> charts) {
        this.name = name;
        this.version = version;
        this.charts = charts;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Version.
     * @return Returns the String
     */
    @JsonGetter("version")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getVersion() {
        return version;
    }

    /**
     * Setter for Version.
     * @param version Value for String
     */
    @JsonSetter("version")
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * Getter for Charts.
     * @return Returns the List of Chart
     */
    @JsonGetter("charts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Chart> getCharts() {
        return charts;
    }

    /**
     * Setter for Charts.
     * @param charts Value for List of Chart
     */
    @JsonSetter("charts")
    public void setCharts(List<Chart> charts) {
        this.charts = charts;
    }

    /**
     * Converts this BillOfMaterialsInformation into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BillOfMaterialsInformation [" + "name=" + name + ", version=" + version
                + ", charts=" + charts + "]";
    }

    /**
     * Builds a new {@link BillOfMaterialsInformation.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BillOfMaterialsInformation.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .name(getName())
                .version(getVersion())
                .charts(getCharts());
        return builder;
    }

    /**
     * Class to build instances of {@link BillOfMaterialsInformation}.
     */
    public static class Builder {
        private String name;
        private String version;
        private List<Chart> charts;



        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for version.
         * @param  version  String value for version.
         * @return Builder
         */
        public Builder version(String version) {
            this.version = version;
            return this;
        }

        /**
         * Setter for charts.
         * @param  charts  List of Chart value for charts.
         * @return Builder
         */
        public Builder charts(List<Chart> charts) {
            this.charts = charts;
            return this;
        }

        /**
         * Builds a new {@link BillOfMaterialsInformation} object using the set fields.
         * @return {@link BillOfMaterialsInformation}
         */
        public BillOfMaterialsInformation build() {
            return new BillOfMaterialsInformation(name, version, charts);
        }
    }
}
