/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.example.www.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * This is a model class for EdgeInstanceHealthDetails type.
 */
public class EdgeInstanceHealthDetails {
    private UUID edgeInstanceId;
    private LocalDateTime timestamp;
    private List<NamespaceStatusDetails> systemstatus;
    private List<NamespaceChartDetails> installedCharts;

    /**
     * Default constructor.
     */
    public EdgeInstanceHealthDetails() {
    }

    /**
     * Initialization constructor.
     * @param  edgeInstanceId  UUID value for edgeInstanceId.
     * @param  timestamp  LocalDateTime value for timestamp.
     * @param  systemstatus  List of NamespaceStatusDetails value for systemstatus.
     * @param  installedCharts  List of NamespaceChartDetails value for installedCharts.
     */
    public EdgeInstanceHealthDetails(
            UUID edgeInstanceId,
            LocalDateTime timestamp,
            List<NamespaceStatusDetails> systemstatus,
            List<NamespaceChartDetails> installedCharts) {
        this.edgeInstanceId = edgeInstanceId;
        this.timestamp = timestamp;
        this.systemstatus = systemstatus;
        this.installedCharts = installedCharts;
    }

    /**
     * Getter for EdgeInstanceId.
     * @return Returns the UUID
     */
    @JsonGetter("edgeInstanceId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getEdgeInstanceId() {
        return edgeInstanceId;
    }

    /**
     * Setter for EdgeInstanceId.
     * @param edgeInstanceId Value for UUID
     */
    @JsonSetter("edgeInstanceId")
    public void setEdgeInstanceId(UUID edgeInstanceId) {
        this.edgeInstanceId = edgeInstanceId;
    }

    /**
     * Getter for Timestamp.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("timestamp")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    /**
     * Setter for Timestamp.
     * @param timestamp Value for LocalDateTime
     */
    @JsonSetter("timestamp")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Getter for Systemstatus.
     * @return Returns the List of NamespaceStatusDetails
     */
    @JsonGetter("systemstatus")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<NamespaceStatusDetails> getSystemstatus() {
        return systemstatus;
    }

    /**
     * Setter for Systemstatus.
     * @param systemstatus Value for List of NamespaceStatusDetails
     */
    @JsonSetter("systemstatus")
    public void setSystemstatus(List<NamespaceStatusDetails> systemstatus) {
        this.systemstatus = systemstatus;
    }

    /**
     * Getter for InstalledCharts.
     * @return Returns the List of NamespaceChartDetails
     */
    @JsonGetter("installedCharts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<NamespaceChartDetails> getInstalledCharts() {
        return installedCharts;
    }

    /**
     * Setter for InstalledCharts.
     * @param installedCharts Value for List of NamespaceChartDetails
     */
    @JsonSetter("installedCharts")
    public void setInstalledCharts(List<NamespaceChartDetails> installedCharts) {
        this.installedCharts = installedCharts;
    }

    /**
     * Converts this EdgeInstanceHealthDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EdgeInstanceHealthDetails [" + "edgeInstanceId=" + edgeInstanceId + ", timestamp="
                + timestamp + ", systemstatus=" + systemstatus + ", installedCharts="
                + installedCharts + "]";
    }

    /**
     * Builds a new {@link EdgeInstanceHealthDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EdgeInstanceHealthDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .edgeInstanceId(getEdgeInstanceId())
                .timestamp(getTimestamp())
                .systemstatus(getSystemstatus())
                .installedCharts(getInstalledCharts());
        return builder;
    }

    /**
     * Class to build instances of {@link EdgeInstanceHealthDetails}.
     */
    public static class Builder {
        private UUID edgeInstanceId;
        private LocalDateTime timestamp;
        private List<NamespaceStatusDetails> systemstatus;
        private List<NamespaceChartDetails> installedCharts;



        /**
         * Setter for edgeInstanceId.
         * @param  edgeInstanceId  UUID value for edgeInstanceId.
         * @return Builder
         */
        public Builder edgeInstanceId(UUID edgeInstanceId) {
            this.edgeInstanceId = edgeInstanceId;
            return this;
        }

        /**
         * Setter for timestamp.
         * @param  timestamp  LocalDateTime value for timestamp.
         * @return Builder
         */
        public Builder timestamp(LocalDateTime timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        /**
         * Setter for systemstatus.
         * @param  systemstatus  List of NamespaceStatusDetails value for systemstatus.
         * @return Builder
         */
        public Builder systemstatus(List<NamespaceStatusDetails> systemstatus) {
            this.systemstatus = systemstatus;
            return this;
        }

        /**
         * Setter for installedCharts.
         * @param  installedCharts  List of NamespaceChartDetails value for installedCharts.
         * @return Builder
         */
        public Builder installedCharts(List<NamespaceChartDetails> installedCharts) {
            this.installedCharts = installedCharts;
            return this;
        }

        /**
         * Builds a new {@link EdgeInstanceHealthDetails} object using the set fields.
         * @return {@link EdgeInstanceHealthDetails}
         */
        public EdgeInstanceHealthDetails build() {
            return new EdgeInstanceHealthDetails(edgeInstanceId, timestamp, systemstatus,
                    installedCharts);
        }
    }
}
