/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for EdgeInstanceRequest type.
 */
public class EdgeInstanceRequest {
    private String name;

    /**
     * Default constructor.
     */
    public EdgeInstanceRequest() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     */
    public EdgeInstanceRequest(
            String name) {
        this.name = name;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Converts this EdgeInstanceRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EdgeInstanceRequest [" + "name=" + name + "]";
    }

    /**
     * Builds a new {@link EdgeInstanceRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EdgeInstanceRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(name);
        return builder;
    }

    /**
     * Class to build instances of {@link EdgeInstanceRequest}.
     */
    public static class Builder {
        private String name;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  name  String value for name.
         */
        public Builder(String name) {
            this.name = name;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Builds a new {@link EdgeInstanceRequest} object using the set fields.
         * @return {@link EdgeInstanceRequest}
         */
        public EdgeInstanceRequest build() {
            return new EdgeInstanceRequest(name);
        }
    }
}
