/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.UUID;

/**
 * This is a model class for EdgeWorkerRequest type.
 */
public class EdgeWorkerRequest {
    private String host;
    private Integer port;
    private UUID edgeInstanceId;

    /**
     * Default constructor.
     */
    public EdgeWorkerRequest() {
    }

    /**
     * Initialization constructor.
     * @param  host  String value for host.
     * @param  port  Integer value for port.
     * @param  edgeInstanceId  UUID value for edgeInstanceId.
     */
    public EdgeWorkerRequest(
            String host,
            Integer port,
            UUID edgeInstanceId) {
        this.host = host;
        this.port = port;
        this.edgeInstanceId = edgeInstanceId;
    }

    /**
     * Getter for Host.
     * @return Returns the String
     */
    @JsonGetter("host")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getHost() {
        return host;
    }

    /**
     * Setter for Host.
     * @param host Value for String
     */
    @JsonSetter("host")
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * Getter for Port.
     * @return Returns the Integer
     */
    @JsonGetter("port")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getPort() {
        return port;
    }

    /**
     * Setter for Port.
     * @param port Value for Integer
     */
    @JsonSetter("port")
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * Getter for EdgeInstanceId.
     * @return Returns the UUID
     */
    @JsonGetter("edgeInstanceId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getEdgeInstanceId() {
        return edgeInstanceId;
    }

    /**
     * Setter for EdgeInstanceId.
     * @param edgeInstanceId Value for UUID
     */
    @JsonSetter("edgeInstanceId")
    public void setEdgeInstanceId(UUID edgeInstanceId) {
        this.edgeInstanceId = edgeInstanceId;
    }

    /**
     * Converts this EdgeWorkerRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EdgeWorkerRequest [" + "host=" + host + ", port=" + port + ", edgeInstanceId="
                + edgeInstanceId + "]";
    }

    /**
     * Builds a new {@link EdgeWorkerRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EdgeWorkerRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .host(getHost())
                .port(getPort())
                .edgeInstanceId(getEdgeInstanceId());
        return builder;
    }

    /**
     * Class to build instances of {@link EdgeWorkerRequest}.
     */
    public static class Builder {
        private String host;
        private Integer port;
        private UUID edgeInstanceId;



        /**
         * Setter for host.
         * @param  host  String value for host.
         * @return Builder
         */
        public Builder host(String host) {
            this.host = host;
            return this;
        }

        /**
         * Setter for port.
         * @param  port  Integer value for port.
         * @return Builder
         */
        public Builder port(Integer port) {
            this.port = port;
            return this;
        }

        /**
         * Setter for edgeInstanceId.
         * @param  edgeInstanceId  UUID value for edgeInstanceId.
         * @return Builder
         */
        public Builder edgeInstanceId(UUID edgeInstanceId) {
            this.edgeInstanceId = edgeInstanceId;
            return this;
        }

        /**
         * Builds a new {@link EdgeWorkerRequest} object using the set fields.
         * @return {@link EdgeWorkerRequest}
         */
        public EdgeWorkerRequest build() {
            return new EdgeWorkerRequest(host, port, edgeInstanceId);
        }
    }
}
