/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.example.www.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * This is a model class for EdgeInstanceInformation type.
 */
public class EdgeInstanceInformation {
    private UUID id;
    private UUID companyId;
    private List<ProductEntitlementEnum> productEntitlements;
    private UUID environmentId;
    private UUID pairingCodeId;
    private String name;
    private EdgeTypeEnum edgeType;
    private EdgeStatusEnum edgeStatus;
    private String clientId;
    private LocalDateTime modificationDate;
    private String address;
    private LocalDateTime deploymentDate;
    private LocalDateTime lastSeenOnDate;
    private EdgeInstanceStatusDetailsInformation statusDetails;
    private List<EdgeWorkerStatusDetailsInformation> workerStatusDetails;
    private Boolean reconciliationFailed;
    private String encryptionKeyId;
    private LocalDateTime encryptionKeyDeploymentDate;
    private Long integrationServicesCount;

    /**
     * Default constructor.
     */
    public EdgeInstanceInformation() {
    }

    /**
     * Initialization constructor.
     * @param  id  UUID value for id.
     * @param  companyId  UUID value for companyId.
     * @param  productEntitlements  List of ProductEntitlementEnum value for productEntitlements.
     * @param  environmentId  UUID value for environmentId.
     * @param  pairingCodeId  UUID value for pairingCodeId.
     * @param  name  String value for name.
     * @param  edgeType  EdgeTypeEnum value for edgeType.
     * @param  edgeStatus  EdgeStatusEnum value for edgeStatus.
     * @param  clientId  String value for clientId.
     * @param  modificationDate  LocalDateTime value for modificationDate.
     * @param  address  String value for address.
     * @param  deploymentDate  LocalDateTime value for deploymentDate.
     * @param  lastSeenOnDate  LocalDateTime value for lastSeenOnDate.
     * @param  statusDetails  EdgeInstanceStatusDetailsInformation value for statusDetails.
     * @param  workerStatusDetails  List of EdgeWorkerStatusDetailsInformation value for
     *         workerStatusDetails.
     * @param  reconciliationFailed  Boolean value for reconciliationFailed.
     * @param  encryptionKeyId  String value for encryptionKeyId.
     * @param  encryptionKeyDeploymentDate  LocalDateTime value for encryptionKeyDeploymentDate.
     * @param  integrationServicesCount  Long value for integrationServicesCount.
     */
    public EdgeInstanceInformation(
            UUID id,
            UUID companyId,
            List<ProductEntitlementEnum> productEntitlements,
            UUID environmentId,
            UUID pairingCodeId,
            String name,
            EdgeTypeEnum edgeType,
            EdgeStatusEnum edgeStatus,
            String clientId,
            LocalDateTime modificationDate,
            String address,
            LocalDateTime deploymentDate,
            LocalDateTime lastSeenOnDate,
            EdgeInstanceStatusDetailsInformation statusDetails,
            List<EdgeWorkerStatusDetailsInformation> workerStatusDetails,
            Boolean reconciliationFailed,
            String encryptionKeyId,
            LocalDateTime encryptionKeyDeploymentDate,
            Long integrationServicesCount) {
        this.id = id;
        this.companyId = companyId;
        this.productEntitlements = productEntitlements;
        this.environmentId = environmentId;
        this.pairingCodeId = pairingCodeId;
        this.name = name;
        this.edgeType = edgeType;
        this.edgeStatus = edgeStatus;
        this.clientId = clientId;
        this.modificationDate = modificationDate;
        this.address = address;
        this.deploymentDate = deploymentDate;
        this.lastSeenOnDate = lastSeenOnDate;
        this.statusDetails = statusDetails;
        this.workerStatusDetails = workerStatusDetails;
        this.reconciliationFailed = reconciliationFailed;
        this.encryptionKeyId = encryptionKeyId;
        this.encryptionKeyDeploymentDate = encryptionKeyDeploymentDate;
        this.integrationServicesCount = integrationServicesCount;
    }

    /**
     * Getter for Id.
     * @return Returns the UUID
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for UUID
     */
    @JsonSetter("id")
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for CompanyId.
     * @return Returns the UUID
     */
    @JsonGetter("companyId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getCompanyId() {
        return companyId;
    }

    /**
     * Setter for CompanyId.
     * @param companyId Value for UUID
     */
    @JsonSetter("companyId")
    public void setCompanyId(UUID companyId) {
        this.companyId = companyId;
    }

    /**
     * Getter for ProductEntitlements.
     * @return Returns the List of ProductEntitlementEnum
     */
    @JsonGetter("productEntitlements")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ProductEntitlementEnum> getProductEntitlements() {
        return productEntitlements;
    }

    /**
     * Setter for ProductEntitlements.
     * @param productEntitlements Value for List of ProductEntitlementEnum
     */
    @JsonSetter("productEntitlements")
    public void setProductEntitlements(List<ProductEntitlementEnum> productEntitlements) {
        this.productEntitlements = productEntitlements;
    }

    /**
     * Getter for EnvironmentId.
     * @return Returns the UUID
     */
    @JsonGetter("environmentId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getEnvironmentId() {
        return environmentId;
    }

    /**
     * Setter for EnvironmentId.
     * @param environmentId Value for UUID
     */
    @JsonSetter("environmentId")
    public void setEnvironmentId(UUID environmentId) {
        this.environmentId = environmentId;
    }

    /**
     * Getter for PairingCodeId.
     * @return Returns the UUID
     */
    @JsonGetter("pairingCodeId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getPairingCodeId() {
        return pairingCodeId;
    }

    /**
     * Setter for PairingCodeId.
     * @param pairingCodeId Value for UUID
     */
    @JsonSetter("pairingCodeId")
    public void setPairingCodeId(UUID pairingCodeId) {
        this.pairingCodeId = pairingCodeId;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for EdgeType.
     * @return Returns the EdgeTypeEnum
     */
    @JsonGetter("edgeType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EdgeTypeEnum getEdgeType() {
        return edgeType;
    }

    /**
     * Setter for EdgeType.
     * @param edgeType Value for EdgeTypeEnum
     */
    @JsonSetter("edgeType")
    public void setEdgeType(EdgeTypeEnum edgeType) {
        this.edgeType = edgeType;
    }

    /**
     * Getter for EdgeStatus.
     * @return Returns the EdgeStatusEnum
     */
    @JsonGetter("edgeStatus")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EdgeStatusEnum getEdgeStatus() {
        return edgeStatus;
    }

    /**
     * Setter for EdgeStatus.
     * @param edgeStatus Value for EdgeStatusEnum
     */
    @JsonSetter("edgeStatus")
    public void setEdgeStatus(EdgeStatusEnum edgeStatus) {
        this.edgeStatus = edgeStatus;
    }

    /**
     * Getter for ClientId.
     * @return Returns the String
     */
    @JsonGetter("clientId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getClientId() {
        return clientId;
    }

    /**
     * Setter for ClientId.
     * @param clientId Value for String
     */
    @JsonSetter("clientId")
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * Getter for ModificationDate.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("modificationDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getModificationDate() {
        return modificationDate;
    }

    /**
     * Setter for ModificationDate.
     * @param modificationDate Value for LocalDateTime
     */
    @JsonSetter("modificationDate")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setModificationDate(LocalDateTime modificationDate) {
        this.modificationDate = modificationDate;
    }

    /**
     * Getter for Address.
     * @return Returns the String
     */
    @JsonGetter("address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAddress() {
        return address;
    }

    /**
     * Setter for Address.
     * @param address Value for String
     */
    @JsonSetter("address")
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Getter for DeploymentDate.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("deploymentDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getDeploymentDate() {
        return deploymentDate;
    }

    /**
     * Setter for DeploymentDate.
     * @param deploymentDate Value for LocalDateTime
     */
    @JsonSetter("deploymentDate")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setDeploymentDate(LocalDateTime deploymentDate) {
        this.deploymentDate = deploymentDate;
    }

    /**
     * Getter for LastSeenOnDate.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("lastSeenOnDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getLastSeenOnDate() {
        return lastSeenOnDate;
    }

    /**
     * Setter for LastSeenOnDate.
     * @param lastSeenOnDate Value for LocalDateTime
     */
    @JsonSetter("lastSeenOnDate")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setLastSeenOnDate(LocalDateTime lastSeenOnDate) {
        this.lastSeenOnDate = lastSeenOnDate;
    }

    /**
     * Getter for StatusDetails.
     * @return Returns the EdgeInstanceStatusDetailsInformation
     */
    @JsonGetter("statusDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EdgeInstanceStatusDetailsInformation getStatusDetails() {
        return statusDetails;
    }

    /**
     * Setter for StatusDetails.
     * @param statusDetails Value for EdgeInstanceStatusDetailsInformation
     */
    @JsonSetter("statusDetails")
    public void setStatusDetails(EdgeInstanceStatusDetailsInformation statusDetails) {
        this.statusDetails = statusDetails;
    }

    /**
     * Getter for WorkerStatusDetails.
     * @return Returns the List of EdgeWorkerStatusDetailsInformation
     */
    @JsonGetter("workerStatusDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<EdgeWorkerStatusDetailsInformation> getWorkerStatusDetails() {
        return workerStatusDetails;
    }

    /**
     * Setter for WorkerStatusDetails.
     * @param workerStatusDetails Value for List of EdgeWorkerStatusDetailsInformation
     */
    @JsonSetter("workerStatusDetails")
    public void setWorkerStatusDetails(List<EdgeWorkerStatusDetailsInformation> workerStatusDetails) {
        this.workerStatusDetails = workerStatusDetails;
    }

    /**
     * Getter for ReconciliationFailed.
     * @return Returns the Boolean
     */
    @JsonGetter("reconciliationFailed")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getReconciliationFailed() {
        return reconciliationFailed;
    }

    /**
     * Setter for ReconciliationFailed.
     * @param reconciliationFailed Value for Boolean
     */
    @JsonSetter("reconciliationFailed")
    public void setReconciliationFailed(Boolean reconciliationFailed) {
        this.reconciliationFailed = reconciliationFailed;
    }

    /**
     * Getter for EncryptionKeyId.
     * @return Returns the String
     */
    @JsonGetter("encryptionKeyId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEncryptionKeyId() {
        return encryptionKeyId;
    }

    /**
     * Setter for EncryptionKeyId.
     * @param encryptionKeyId Value for String
     */
    @JsonSetter("encryptionKeyId")
    public void setEncryptionKeyId(String encryptionKeyId) {
        this.encryptionKeyId = encryptionKeyId;
    }

    /**
     * Getter for EncryptionKeyDeploymentDate.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("encryptionKeyDeploymentDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getEncryptionKeyDeploymentDate() {
        return encryptionKeyDeploymentDate;
    }

    /**
     * Setter for EncryptionKeyDeploymentDate.
     * @param encryptionKeyDeploymentDate Value for LocalDateTime
     */
    @JsonSetter("encryptionKeyDeploymentDate")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setEncryptionKeyDeploymentDate(LocalDateTime encryptionKeyDeploymentDate) {
        this.encryptionKeyDeploymentDate = encryptionKeyDeploymentDate;
    }

    /**
     * Getter for IntegrationServicesCount.
     * @return Returns the Long
     */
    @JsonGetter("integrationServicesCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Long getIntegrationServicesCount() {
        return integrationServicesCount;
    }

    /**
     * Setter for IntegrationServicesCount.
     * @param integrationServicesCount Value for Long
     */
    @JsonSetter("integrationServicesCount")
    public void setIntegrationServicesCount(Long integrationServicesCount) {
        this.integrationServicesCount = integrationServicesCount;
    }

    /**
     * Converts this EdgeInstanceInformation into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EdgeInstanceInformation [" + "id=" + id + ", companyId=" + companyId
                + ", productEntitlements=" + productEntitlements + ", environmentId="
                + environmentId + ", pairingCodeId=" + pairingCodeId + ", name=" + name
                + ", edgeType=" + edgeType + ", edgeStatus=" + edgeStatus + ", clientId=" + clientId
                + ", modificationDate=" + modificationDate + ", address=" + address
                + ", deploymentDate=" + deploymentDate + ", lastSeenOnDate=" + lastSeenOnDate
                + ", statusDetails=" + statusDetails + ", workerStatusDetails="
                + workerStatusDetails + ", reconciliationFailed=" + reconciliationFailed
                + ", encryptionKeyId=" + encryptionKeyId + ", encryptionKeyDeploymentDate="
                + encryptionKeyDeploymentDate + ", integrationServicesCount="
                + integrationServicesCount + "]";
    }

    /**
     * Builds a new {@link EdgeInstanceInformation.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EdgeInstanceInformation.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .companyId(getCompanyId())
                .productEntitlements(getProductEntitlements())
                .environmentId(getEnvironmentId())
                .pairingCodeId(getPairingCodeId())
                .name(getName())
                .edgeType(getEdgeType())
                .edgeStatus(getEdgeStatus())
                .clientId(getClientId())
                .modificationDate(getModificationDate())
                .address(getAddress())
                .deploymentDate(getDeploymentDate())
                .lastSeenOnDate(getLastSeenOnDate())
                .statusDetails(getStatusDetails())
                .workerStatusDetails(getWorkerStatusDetails())
                .reconciliationFailed(getReconciliationFailed())
                .encryptionKeyId(getEncryptionKeyId())
                .encryptionKeyDeploymentDate(getEncryptionKeyDeploymentDate())
                .integrationServicesCount(getIntegrationServicesCount());
        return builder;
    }

    /**
     * Class to build instances of {@link EdgeInstanceInformation}.
     */
    public static class Builder {
        private UUID id;
        private UUID companyId;
        private List<ProductEntitlementEnum> productEntitlements;
        private UUID environmentId;
        private UUID pairingCodeId;
        private String name;
        private EdgeTypeEnum edgeType;
        private EdgeStatusEnum edgeStatus;
        private String clientId;
        private LocalDateTime modificationDate;
        private String address;
        private LocalDateTime deploymentDate;
        private LocalDateTime lastSeenOnDate;
        private EdgeInstanceStatusDetailsInformation statusDetails;
        private List<EdgeWorkerStatusDetailsInformation> workerStatusDetails;
        private Boolean reconciliationFailed;
        private String encryptionKeyId;
        private LocalDateTime encryptionKeyDeploymentDate;
        private Long integrationServicesCount;



        /**
         * Setter for id.
         * @param  id  UUID value for id.
         * @return Builder
         */
        public Builder id(UUID id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for companyId.
         * @param  companyId  UUID value for companyId.
         * @return Builder
         */
        public Builder companyId(UUID companyId) {
            this.companyId = companyId;
            return this;
        }

        /**
         * Setter for productEntitlements.
         * @param  productEntitlements  List of ProductEntitlementEnum value for
         *         productEntitlements.
         * @return Builder
         */
        public Builder productEntitlements(List<ProductEntitlementEnum> productEntitlements) {
            this.productEntitlements = productEntitlements;
            return this;
        }

        /**
         * Setter for environmentId.
         * @param  environmentId  UUID value for environmentId.
         * @return Builder
         */
        public Builder environmentId(UUID environmentId) {
            this.environmentId = environmentId;
            return this;
        }

        /**
         * Setter for pairingCodeId.
         * @param  pairingCodeId  UUID value for pairingCodeId.
         * @return Builder
         */
        public Builder pairingCodeId(UUID pairingCodeId) {
            this.pairingCodeId = pairingCodeId;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for edgeType.
         * @param  edgeType  EdgeTypeEnum value for edgeType.
         * @return Builder
         */
        public Builder edgeType(EdgeTypeEnum edgeType) {
            this.edgeType = edgeType;
            return this;
        }

        /**
         * Setter for edgeStatus.
         * @param  edgeStatus  EdgeStatusEnum value for edgeStatus.
         * @return Builder
         */
        public Builder edgeStatus(EdgeStatusEnum edgeStatus) {
            this.edgeStatus = edgeStatus;
            return this;
        }

        /**
         * Setter for clientId.
         * @param  clientId  String value for clientId.
         * @return Builder
         */
        public Builder clientId(String clientId) {
            this.clientId = clientId;
            return this;
        }

        /**
         * Setter for modificationDate.
         * @param  modificationDate  LocalDateTime value for modificationDate.
         * @return Builder
         */
        public Builder modificationDate(LocalDateTime modificationDate) {
            this.modificationDate = modificationDate;
            return this;
        }

        /**
         * Setter for address.
         * @param  address  String value for address.
         * @return Builder
         */
        public Builder address(String address) {
            this.address = address;
            return this;
        }

        /**
         * Setter for deploymentDate.
         * @param  deploymentDate  LocalDateTime value for deploymentDate.
         * @return Builder
         */
        public Builder deploymentDate(LocalDateTime deploymentDate) {
            this.deploymentDate = deploymentDate;
            return this;
        }

        /**
         * Setter for lastSeenOnDate.
         * @param  lastSeenOnDate  LocalDateTime value for lastSeenOnDate.
         * @return Builder
         */
        public Builder lastSeenOnDate(LocalDateTime lastSeenOnDate) {
            this.lastSeenOnDate = lastSeenOnDate;
            return this;
        }

        /**
         * Setter for statusDetails.
         * @param  statusDetails  EdgeInstanceStatusDetailsInformation value for statusDetails.
         * @return Builder
         */
        public Builder statusDetails(EdgeInstanceStatusDetailsInformation statusDetails) {
            this.statusDetails = statusDetails;
            return this;
        }

        /**
         * Setter for workerStatusDetails.
         * @param  workerStatusDetails  List of EdgeWorkerStatusDetailsInformation value for
         *         workerStatusDetails.
         * @return Builder
         */
        public Builder workerStatusDetails(
                List<EdgeWorkerStatusDetailsInformation> workerStatusDetails) {
            this.workerStatusDetails = workerStatusDetails;
            return this;
        }

        /**
         * Setter for reconciliationFailed.
         * @param  reconciliationFailed  Boolean value for reconciliationFailed.
         * @return Builder
         */
        public Builder reconciliationFailed(Boolean reconciliationFailed) {
            this.reconciliationFailed = reconciliationFailed;
            return this;
        }

        /**
         * Setter for encryptionKeyId.
         * @param  encryptionKeyId  String value for encryptionKeyId.
         * @return Builder
         */
        public Builder encryptionKeyId(String encryptionKeyId) {
            this.encryptionKeyId = encryptionKeyId;
            return this;
        }

        /**
         * Setter for encryptionKeyDeploymentDate.
         * @param  encryptionKeyDeploymentDate  LocalDateTime value for encryptionKeyDeploymentDate.
         * @return Builder
         */
        public Builder encryptionKeyDeploymentDate(LocalDateTime encryptionKeyDeploymentDate) {
            this.encryptionKeyDeploymentDate = encryptionKeyDeploymentDate;
            return this;
        }

        /**
         * Setter for integrationServicesCount.
         * @param  integrationServicesCount  Long value for integrationServicesCount.
         * @return Builder
         */
        public Builder integrationServicesCount(Long integrationServicesCount) {
            this.integrationServicesCount = integrationServicesCount;
            return this;
        }

        /**
         * Builds a new {@link EdgeInstanceInformation} object using the set fields.
         * @return {@link EdgeInstanceInformation}
         */
        public EdgeInstanceInformation build() {
            return new EdgeInstanceInformation(id, companyId, productEntitlements, environmentId,
                    pairingCodeId, name, edgeType, edgeStatus, clientId, modificationDate, address,
                    deploymentDate, lastSeenOnDate, statusDetails, workerStatusDetails,
                    reconciliationFailed, encryptionKeyId, encryptionKeyDeploymentDate,
                    integrationServicesCount);
        }
    }
}
