/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for EdgeInstanceStatusDetailsInformation type.
 */
public class EdgeInstanceStatusDetailsInformation {
    private List<EdgeInstanceConnectionDetails> connectionDetails;
    private List<EdgeInstanceHealthDetails> healthDetails;

    /**
     * Default constructor.
     */
    public EdgeInstanceStatusDetailsInformation() {
    }

    /**
     * Initialization constructor.
     * @param  connectionDetails  List of EdgeInstanceConnectionDetails value for connectionDetails.
     * @param  healthDetails  List of EdgeInstanceHealthDetails value for healthDetails.
     */
    public EdgeInstanceStatusDetailsInformation(
            List<EdgeInstanceConnectionDetails> connectionDetails,
            List<EdgeInstanceHealthDetails> healthDetails) {
        this.connectionDetails = connectionDetails;
        this.healthDetails = healthDetails;
    }

    /**
     * Getter for ConnectionDetails.
     * @return Returns the List of EdgeInstanceConnectionDetails
     */
    @JsonGetter("connectionDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<EdgeInstanceConnectionDetails> getConnectionDetails() {
        return connectionDetails;
    }

    /**
     * Setter for ConnectionDetails.
     * @param connectionDetails Value for List of EdgeInstanceConnectionDetails
     */
    @JsonSetter("connectionDetails")
    public void setConnectionDetails(List<EdgeInstanceConnectionDetails> connectionDetails) {
        this.connectionDetails = connectionDetails;
    }

    /**
     * Getter for HealthDetails.
     * @return Returns the List of EdgeInstanceHealthDetails
     */
    @JsonGetter("healthDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<EdgeInstanceHealthDetails> getHealthDetails() {
        return healthDetails;
    }

    /**
     * Setter for HealthDetails.
     * @param healthDetails Value for List of EdgeInstanceHealthDetails
     */
    @JsonSetter("healthDetails")
    public void setHealthDetails(List<EdgeInstanceHealthDetails> healthDetails) {
        this.healthDetails = healthDetails;
    }

    /**
     * Converts this EdgeInstanceStatusDetailsInformation into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EdgeInstanceStatusDetailsInformation [" + "connectionDetails=" + connectionDetails
                + ", healthDetails=" + healthDetails + "]";
    }

    /**
     * Builds a new {@link EdgeInstanceStatusDetailsInformation.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EdgeInstanceStatusDetailsInformation.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .connectionDetails(getConnectionDetails())
                .healthDetails(getHealthDetails());
        return builder;
    }

    /**
     * Class to build instances of {@link EdgeInstanceStatusDetailsInformation}.
     */
    public static class Builder {
        private List<EdgeInstanceConnectionDetails> connectionDetails;
        private List<EdgeInstanceHealthDetails> healthDetails;



        /**
         * Setter for connectionDetails.
         * @param  connectionDetails  List of EdgeInstanceConnectionDetails value for
         *         connectionDetails.
         * @return Builder
         */
        public Builder connectionDetails(List<EdgeInstanceConnectionDetails> connectionDetails) {
            this.connectionDetails = connectionDetails;
            return this;
        }

        /**
         * Setter for healthDetails.
         * @param  healthDetails  List of EdgeInstanceHealthDetails value for healthDetails.
         * @return Builder
         */
        public Builder healthDetails(List<EdgeInstanceHealthDetails> healthDetails) {
            this.healthDetails = healthDetails;
            return this;
        }

        /**
         * Builds a new {@link EdgeInstanceStatusDetailsInformation} object using the set fields.
         * @return {@link EdgeInstanceStatusDetailsInformation}
         */
        public EdgeInstanceStatusDetailsInformation build() {
            return new EdgeInstanceStatusDetailsInformation(connectionDetails, healthDetails);
        }
    }
}
