/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for EdgeInstanceResponse type.
 */
public class EdgeInstanceResponse {
    private List<EdgeInstanceInformation> edgeInstances;

    /**
     * Default constructor.
     */
    public EdgeInstanceResponse() {
    }

    /**
     * Initialization constructor.
     * @param  edgeInstances  List of EdgeInstanceInformation value for edgeInstances.
     */
    public EdgeInstanceResponse(
            List<EdgeInstanceInformation> edgeInstances) {
        this.edgeInstances = edgeInstances;
    }

    /**
     * Getter for EdgeInstances.
     * @return Returns the List of EdgeInstanceInformation
     */
    @JsonGetter("edgeInstances")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<EdgeInstanceInformation> getEdgeInstances() {
        return edgeInstances;
    }

    /**
     * Setter for EdgeInstances.
     * @param edgeInstances Value for List of EdgeInstanceInformation
     */
    @JsonSetter("edgeInstances")
    public void setEdgeInstances(List<EdgeInstanceInformation> edgeInstances) {
        this.edgeInstances = edgeInstances;
    }

    /**
     * Converts this EdgeInstanceResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EdgeInstanceResponse [" + "edgeInstances=" + edgeInstances + "]";
    }

    /**
     * Builds a new {@link EdgeInstanceResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EdgeInstanceResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .edgeInstances(getEdgeInstances());
        return builder;
    }

    /**
     * Class to build instances of {@link EdgeInstanceResponse}.
     */
    public static class Builder {
        private List<EdgeInstanceInformation> edgeInstances;



        /**
         * Setter for edgeInstances.
         * @param  edgeInstances  List of EdgeInstanceInformation value for edgeInstances.
         * @return Builder
         */
        public Builder edgeInstances(List<EdgeInstanceInformation> edgeInstances) {
            this.edgeInstances = edgeInstances;
            return this;
        }

        /**
         * Builds a new {@link EdgeInstanceResponse} object using the set fields.
         * @return {@link EdgeInstanceResponse}
         */
        public EdgeInstanceResponse build() {
            return new EdgeInstanceResponse(edgeInstances);
        }
    }
}
