/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * EdgeTypeEnum to be used.
 */
public enum EdgeTypeEnum {
    ALL,

    HUB,

    SATELLITE;


    private static TreeMap<String, EdgeTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ALL.value = "ALL";
        HUB.value = "HUB";
        SATELLITE.value = "SATELLITE";

        valueMap.put("ALL", ALL);
        valueMap.put("HUB", HUB);
        valueMap.put("SATELLITE", SATELLITE);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static EdgeTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of EdgeTypeEnum values to list of string values.
     * @param toConvert The list of EdgeTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<EdgeTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (EdgeTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 