/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.example.www.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * This is a model class for EdgeWorkerHealthDetails type.
 */
public class EdgeWorkerHealthDetails {
    private UUID edgeWorkerId;
    private UUID edgeInstanceId;
    private LocalDateTime timestamp;
    private String host;
    private Integer port;
    private String status;
    private Long age;
    private Integer cpuUsage;
    private Long memoryUsage;
    private List<WorkerServiceStatusDetails> services;

    /**
     * Default constructor.
     */
    public EdgeWorkerHealthDetails() {
    }

    /**
     * Initialization constructor.
     * @param  edgeWorkerId  UUID value for edgeWorkerId.
     * @param  edgeInstanceId  UUID value for edgeInstanceId.
     * @param  timestamp  LocalDateTime value for timestamp.
     * @param  host  String value for host.
     * @param  port  Integer value for port.
     * @param  status  String value for status.
     * @param  age  Long value for age.
     * @param  cpuUsage  Integer value for cpuUsage.
     * @param  memoryUsage  Long value for memoryUsage.
     * @param  services  List of WorkerServiceStatusDetails value for services.
     */
    public EdgeWorkerHealthDetails(
            UUID edgeWorkerId,
            UUID edgeInstanceId,
            LocalDateTime timestamp,
            String host,
            Integer port,
            String status,
            Long age,
            Integer cpuUsage,
            Long memoryUsage,
            List<WorkerServiceStatusDetails> services) {
        this.edgeWorkerId = edgeWorkerId;
        this.edgeInstanceId = edgeInstanceId;
        this.timestamp = timestamp;
        this.host = host;
        this.port = port;
        this.status = status;
        this.age = age;
        this.cpuUsage = cpuUsage;
        this.memoryUsage = memoryUsage;
        this.services = services;
    }

    /**
     * Getter for EdgeWorkerId.
     * @return Returns the UUID
     */
    @JsonGetter("edgeWorkerId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getEdgeWorkerId() {
        return edgeWorkerId;
    }

    /**
     * Setter for EdgeWorkerId.
     * @param edgeWorkerId Value for UUID
     */
    @JsonSetter("edgeWorkerId")
    public void setEdgeWorkerId(UUID edgeWorkerId) {
        this.edgeWorkerId = edgeWorkerId;
    }

    /**
     * Getter for EdgeInstanceId.
     * @return Returns the UUID
     */
    @JsonGetter("edgeInstanceId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getEdgeInstanceId() {
        return edgeInstanceId;
    }

    /**
     * Setter for EdgeInstanceId.
     * @param edgeInstanceId Value for UUID
     */
    @JsonSetter("edgeInstanceId")
    public void setEdgeInstanceId(UUID edgeInstanceId) {
        this.edgeInstanceId = edgeInstanceId;
    }

    /**
     * Getter for Timestamp.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("timestamp")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    /**
     * Setter for Timestamp.
     * @param timestamp Value for LocalDateTime
     */
    @JsonSetter("timestamp")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Getter for Host.
     * @return Returns the String
     */
    @JsonGetter("host")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getHost() {
        return host;
    }

    /**
     * Setter for Host.
     * @param host Value for String
     */
    @JsonSetter("host")
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * Getter for Port.
     * @return Returns the Integer
     */
    @JsonGetter("port")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getPort() {
        return port;
    }

    /**
     * Setter for Port.
     * @param port Value for Integer
     */
    @JsonSetter("port")
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for Age.
     * @return Returns the Long
     */
    @JsonGetter("age")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Long getAge() {
        return age;
    }

    /**
     * Setter for Age.
     * @param age Value for Long
     */
    @JsonSetter("age")
    public void setAge(Long age) {
        this.age = age;
    }

    /**
     * Getter for CpuUsage.
     * @return Returns the Integer
     */
    @JsonGetter("cpuUsage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCpuUsage() {
        return cpuUsage;
    }

    /**
     * Setter for CpuUsage.
     * @param cpuUsage Value for Integer
     */
    @JsonSetter("cpuUsage")
    public void setCpuUsage(Integer cpuUsage) {
        this.cpuUsage = cpuUsage;
    }

    /**
     * Getter for MemoryUsage.
     * @return Returns the Long
     */
    @JsonGetter("memoryUsage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Long getMemoryUsage() {
        return memoryUsage;
    }

    /**
     * Setter for MemoryUsage.
     * @param memoryUsage Value for Long
     */
    @JsonSetter("memoryUsage")
    public void setMemoryUsage(Long memoryUsage) {
        this.memoryUsage = memoryUsage;
    }

    /**
     * Getter for Services.
     * @return Returns the List of WorkerServiceStatusDetails
     */
    @JsonGetter("services")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<WorkerServiceStatusDetails> getServices() {
        return services;
    }

    /**
     * Setter for Services.
     * @param services Value for List of WorkerServiceStatusDetails
     */
    @JsonSetter("services")
    public void setServices(List<WorkerServiceStatusDetails> services) {
        this.services = services;
    }

    /**
     * Converts this EdgeWorkerHealthDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EdgeWorkerHealthDetails [" + "edgeWorkerId=" + edgeWorkerId + ", edgeInstanceId="
                + edgeInstanceId + ", timestamp=" + timestamp + ", host=" + host + ", port=" + port
                + ", status=" + status + ", age=" + age + ", cpuUsage=" + cpuUsage
                + ", memoryUsage=" + memoryUsage + ", services=" + services + "]";
    }

    /**
     * Builds a new {@link EdgeWorkerHealthDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EdgeWorkerHealthDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .edgeWorkerId(getEdgeWorkerId())
                .edgeInstanceId(getEdgeInstanceId())
                .timestamp(getTimestamp())
                .host(getHost())
                .port(getPort())
                .status(getStatus())
                .age(getAge())
                .cpuUsage(getCpuUsage())
                .memoryUsage(getMemoryUsage())
                .services(getServices());
        return builder;
    }

    /**
     * Class to build instances of {@link EdgeWorkerHealthDetails}.
     */
    public static class Builder {
        private UUID edgeWorkerId;
        private UUID edgeInstanceId;
        private LocalDateTime timestamp;
        private String host;
        private Integer port;
        private String status;
        private Long age;
        private Integer cpuUsage;
        private Long memoryUsage;
        private List<WorkerServiceStatusDetails> services;



        /**
         * Setter for edgeWorkerId.
         * @param  edgeWorkerId  UUID value for edgeWorkerId.
         * @return Builder
         */
        public Builder edgeWorkerId(UUID edgeWorkerId) {
            this.edgeWorkerId = edgeWorkerId;
            return this;
        }

        /**
         * Setter for edgeInstanceId.
         * @param  edgeInstanceId  UUID value for edgeInstanceId.
         * @return Builder
         */
        public Builder edgeInstanceId(UUID edgeInstanceId) {
            this.edgeInstanceId = edgeInstanceId;
            return this;
        }

        /**
         * Setter for timestamp.
         * @param  timestamp  LocalDateTime value for timestamp.
         * @return Builder
         */
        public Builder timestamp(LocalDateTime timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        /**
         * Setter for host.
         * @param  host  String value for host.
         * @return Builder
         */
        public Builder host(String host) {
            this.host = host;
            return this;
        }

        /**
         * Setter for port.
         * @param  port  Integer value for port.
         * @return Builder
         */
        public Builder port(Integer port) {
            this.port = port;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for age.
         * @param  age  Long value for age.
         * @return Builder
         */
        public Builder age(Long age) {
            this.age = age;
            return this;
        }

        /**
         * Setter for cpuUsage.
         * @param  cpuUsage  Integer value for cpuUsage.
         * @return Builder
         */
        public Builder cpuUsage(Integer cpuUsage) {
            this.cpuUsage = cpuUsage;
            return this;
        }

        /**
         * Setter for memoryUsage.
         * @param  memoryUsage  Long value for memoryUsage.
         * @return Builder
         */
        public Builder memoryUsage(Long memoryUsage) {
            this.memoryUsage = memoryUsage;
            return this;
        }

        /**
         * Setter for services.
         * @param  services  List of WorkerServiceStatusDetails value for services.
         * @return Builder
         */
        public Builder services(List<WorkerServiceStatusDetails> services) {
            this.services = services;
            return this;
        }

        /**
         * Builds a new {@link EdgeWorkerHealthDetails} object using the set fields.
         * @return {@link EdgeWorkerHealthDetails}
         */
        public EdgeWorkerHealthDetails build() {
            return new EdgeWorkerHealthDetails(edgeWorkerId, edgeInstanceId, timestamp, host, port,
                    status, age, cpuUsage, memoryUsage, services);
        }
    }
}
