/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.example.www.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * This is a model class for EdgeWorkerInformation type.
 */
public class EdgeWorkerInformation {
    private UUID id;
    private UUID companyId;
    private String host;
    private Integer port;
    private String pairingCode;
    private String pairingPublicKey;
    private UUID edgeInstanceId;
    private UUID environmentId;
    private StatusEnum status;
    private LocalDateTime lastSeenOnDate;

    /**
     * Default constructor.
     */
    public EdgeWorkerInformation() {
    }

    /**
     * Initialization constructor.
     * @param  id  UUID value for id.
     * @param  companyId  UUID value for companyId.
     * @param  host  String value for host.
     * @param  port  Integer value for port.
     * @param  pairingCode  String value for pairingCode.
     * @param  pairingPublicKey  String value for pairingPublicKey.
     * @param  edgeInstanceId  UUID value for edgeInstanceId.
     * @param  environmentId  UUID value for environmentId.
     * @param  status  StatusEnum value for status.
     * @param  lastSeenOnDate  LocalDateTime value for lastSeenOnDate.
     */
    public EdgeWorkerInformation(
            UUID id,
            UUID companyId,
            String host,
            Integer port,
            String pairingCode,
            String pairingPublicKey,
            UUID edgeInstanceId,
            UUID environmentId,
            StatusEnum status,
            LocalDateTime lastSeenOnDate) {
        this.id = id;
        this.companyId = companyId;
        this.host = host;
        this.port = port;
        this.pairingCode = pairingCode;
        this.pairingPublicKey = pairingPublicKey;
        this.edgeInstanceId = edgeInstanceId;
        this.environmentId = environmentId;
        this.status = status;
        this.lastSeenOnDate = lastSeenOnDate;
    }

    /**
     * Getter for Id.
     * @return Returns the UUID
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for UUID
     */
    @JsonSetter("id")
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for CompanyId.
     * @return Returns the UUID
     */
    @JsonGetter("companyId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getCompanyId() {
        return companyId;
    }

    /**
     * Setter for CompanyId.
     * @param companyId Value for UUID
     */
    @JsonSetter("companyId")
    public void setCompanyId(UUID companyId) {
        this.companyId = companyId;
    }

    /**
     * Getter for Host.
     * @return Returns the String
     */
    @JsonGetter("host")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getHost() {
        return host;
    }

    /**
     * Setter for Host.
     * @param host Value for String
     */
    @JsonSetter("host")
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * Getter for Port.
     * @return Returns the Integer
     */
    @JsonGetter("port")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getPort() {
        return port;
    }

    /**
     * Setter for Port.
     * @param port Value for Integer
     */
    @JsonSetter("port")
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * Getter for PairingCode.
     * @return Returns the String
     */
    @JsonGetter("pairingCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPairingCode() {
        return pairingCode;
    }

    /**
     * Setter for PairingCode.
     * @param pairingCode Value for String
     */
    @JsonSetter("pairingCode")
    public void setPairingCode(String pairingCode) {
        this.pairingCode = pairingCode;
    }

    /**
     * Getter for PairingPublicKey.
     * @return Returns the String
     */
    @JsonGetter("pairingPublicKey")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPairingPublicKey() {
        return pairingPublicKey;
    }

    /**
     * Setter for PairingPublicKey.
     * @param pairingPublicKey Value for String
     */
    @JsonSetter("pairingPublicKey")
    public void setPairingPublicKey(String pairingPublicKey) {
        this.pairingPublicKey = pairingPublicKey;
    }

    /**
     * Getter for EdgeInstanceId.
     * @return Returns the UUID
     */
    @JsonGetter("edgeInstanceId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getEdgeInstanceId() {
        return edgeInstanceId;
    }

    /**
     * Setter for EdgeInstanceId.
     * @param edgeInstanceId Value for UUID
     */
    @JsonSetter("edgeInstanceId")
    public void setEdgeInstanceId(UUID edgeInstanceId) {
        this.edgeInstanceId = edgeInstanceId;
    }

    /**
     * Getter for EnvironmentId.
     * @return Returns the UUID
     */
    @JsonGetter("environmentId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getEnvironmentId() {
        return environmentId;
    }

    /**
     * Setter for EnvironmentId.
     * @param environmentId Value for UUID
     */
    @JsonSetter("environmentId")
    public void setEnvironmentId(UUID environmentId) {
        this.environmentId = environmentId;
    }

    /**
     * Getter for Status.
     * @return Returns the StatusEnum
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public StatusEnum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for StatusEnum
     */
    @JsonSetter("status")
    public void setStatus(StatusEnum status) {
        this.status = status;
    }

    /**
     * Getter for LastSeenOnDate.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("lastSeenOnDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getLastSeenOnDate() {
        return lastSeenOnDate;
    }

    /**
     * Setter for LastSeenOnDate.
     * @param lastSeenOnDate Value for LocalDateTime
     */
    @JsonSetter("lastSeenOnDate")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setLastSeenOnDate(LocalDateTime lastSeenOnDate) {
        this.lastSeenOnDate = lastSeenOnDate;
    }

    /**
     * Converts this EdgeWorkerInformation into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EdgeWorkerInformation [" + "id=" + id + ", companyId=" + companyId + ", host="
                + host + ", port=" + port + ", pairingCode=" + pairingCode + ", pairingPublicKey="
                + pairingPublicKey + ", edgeInstanceId=" + edgeInstanceId + ", environmentId="
                + environmentId + ", status=" + status + ", lastSeenOnDate=" + lastSeenOnDate + "]";
    }

    /**
     * Builds a new {@link EdgeWorkerInformation.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EdgeWorkerInformation.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .companyId(getCompanyId())
                .host(getHost())
                .port(getPort())
                .pairingCode(getPairingCode())
                .pairingPublicKey(getPairingPublicKey())
                .edgeInstanceId(getEdgeInstanceId())
                .environmentId(getEnvironmentId())
                .status(getStatus())
                .lastSeenOnDate(getLastSeenOnDate());
        return builder;
    }

    /**
     * Class to build instances of {@link EdgeWorkerInformation}.
     */
    public static class Builder {
        private UUID id;
        private UUID companyId;
        private String host;
        private Integer port;
        private String pairingCode;
        private String pairingPublicKey;
        private UUID edgeInstanceId;
        private UUID environmentId;
        private StatusEnum status;
        private LocalDateTime lastSeenOnDate;



        /**
         * Setter for id.
         * @param  id  UUID value for id.
         * @return Builder
         */
        public Builder id(UUID id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for companyId.
         * @param  companyId  UUID value for companyId.
         * @return Builder
         */
        public Builder companyId(UUID companyId) {
            this.companyId = companyId;
            return this;
        }

        /**
         * Setter for host.
         * @param  host  String value for host.
         * @return Builder
         */
        public Builder host(String host) {
            this.host = host;
            return this;
        }

        /**
         * Setter for port.
         * @param  port  Integer value for port.
         * @return Builder
         */
        public Builder port(Integer port) {
            this.port = port;
            return this;
        }

        /**
         * Setter for pairingCode.
         * @param  pairingCode  String value for pairingCode.
         * @return Builder
         */
        public Builder pairingCode(String pairingCode) {
            this.pairingCode = pairingCode;
            return this;
        }

        /**
         * Setter for pairingPublicKey.
         * @param  pairingPublicKey  String value for pairingPublicKey.
         * @return Builder
         */
        public Builder pairingPublicKey(String pairingPublicKey) {
            this.pairingPublicKey = pairingPublicKey;
            return this;
        }

        /**
         * Setter for edgeInstanceId.
         * @param  edgeInstanceId  UUID value for edgeInstanceId.
         * @return Builder
         */
        public Builder edgeInstanceId(UUID edgeInstanceId) {
            this.edgeInstanceId = edgeInstanceId;
            return this;
        }

        /**
         * Setter for environmentId.
         * @param  environmentId  UUID value for environmentId.
         * @return Builder
         */
        public Builder environmentId(UUID environmentId) {
            this.environmentId = environmentId;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  StatusEnum value for status.
         * @return Builder
         */
        public Builder status(StatusEnum status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for lastSeenOnDate.
         * @param  lastSeenOnDate  LocalDateTime value for lastSeenOnDate.
         * @return Builder
         */
        public Builder lastSeenOnDate(LocalDateTime lastSeenOnDate) {
            this.lastSeenOnDate = lastSeenOnDate;
            return this;
        }

        /**
         * Builds a new {@link EdgeWorkerInformation} object using the set fields.
         * @return {@link EdgeWorkerInformation}
         */
        public EdgeWorkerInformation build() {
            return new EdgeWorkerInformation(id, companyId, host, port, pairingCode,
                    pairingPublicKey, edgeInstanceId, environmentId, status, lastSeenOnDate);
        }
    }
}
