/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for EdgeWorkersResponse type.
 */
public class EdgeWorkersResponse {
    private List<EdgeWorkerInformation> edgeWorkers;

    /**
     * Default constructor.
     */
    public EdgeWorkersResponse() {
    }

    /**
     * Initialization constructor.
     * @param  edgeWorkers  List of EdgeWorkerInformation value for edgeWorkers.
     */
    public EdgeWorkersResponse(
            List<EdgeWorkerInformation> edgeWorkers) {
        this.edgeWorkers = edgeWorkers;
    }

    /**
     * Getter for EdgeWorkers.
     * @return Returns the List of EdgeWorkerInformation
     */
    @JsonGetter("edgeWorkers")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<EdgeWorkerInformation> getEdgeWorkers() {
        return edgeWorkers;
    }

    /**
     * Setter for EdgeWorkers.
     * @param edgeWorkers Value for List of EdgeWorkerInformation
     */
    @JsonSetter("edgeWorkers")
    public void setEdgeWorkers(List<EdgeWorkerInformation> edgeWorkers) {
        this.edgeWorkers = edgeWorkers;
    }

    /**
     * Converts this EdgeWorkersResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EdgeWorkersResponse [" + "edgeWorkers=" + edgeWorkers + "]";
    }

    /**
     * Builds a new {@link EdgeWorkersResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EdgeWorkersResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .edgeWorkers(getEdgeWorkers());
        return builder;
    }

    /**
     * Class to build instances of {@link EdgeWorkersResponse}.
     */
    public static class Builder {
        private List<EdgeWorkerInformation> edgeWorkers;



        /**
         * Setter for edgeWorkers.
         * @param  edgeWorkers  List of EdgeWorkerInformation value for edgeWorkers.
         * @return Builder
         */
        public Builder edgeWorkers(List<EdgeWorkerInformation> edgeWorkers) {
            this.edgeWorkers = edgeWorkers;
            return this;
        }

        /**
         * Builds a new {@link EdgeWorkersResponse} object using the set fields.
         * @return {@link EdgeWorkersResponse}
         */
        public EdgeWorkersResponse build() {
            return new EdgeWorkersResponse(edgeWorkers);
        }
    }
}
