/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * EdgeStatusEnum to be used.
 */
public enum EdgeStatusEnum {
    ACTIVE,

    LOST_CONNECTION,

    REGISTERED,

    PAIRED,

    LOST_CONNECTION_DURING_INSTALL,

    INSTALLED,

    INSTALL_FAILED,

    UNHEALTHY,

    ERROR,

    INSTALLING;


    private static TreeMap<String, EdgeStatusEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ACTIVE.value = "ACTIVE";
        LOST_CONNECTION.value = "LOST_CONNECTION";
        REGISTERED.value = "REGISTERED";
        PAIRED.value = "PAIRED";
        LOST_CONNECTION_DURING_INSTALL.value = "LOST_CONNECTION_DURING_INSTALL";
        INSTALLED.value = "INSTALLED";
        INSTALL_FAILED.value = "INSTALL_FAILED";
        UNHEALTHY.value = "UNHEALTHY";
        ERROR.value = "ERROR";
        INSTALLING.value = "INSTALLING";

        valueMap.put("ACTIVE", ACTIVE);
        valueMap.put("LOST_CONNECTION", LOST_CONNECTION);
        valueMap.put("REGISTERED", REGISTERED);
        valueMap.put("PAIRED", PAIRED);
        valueMap.put("LOST_CONNECTION_DURING_INSTALL", LOST_CONNECTION_DURING_INSTALL);
        valueMap.put("INSTALLED", INSTALLED);
        valueMap.put("INSTALL_FAILED", INSTALL_FAILED);
        valueMap.put("UNHEALTHY", UNHEALTHY);
        valueMap.put("ERROR", ERROR);
        valueMap.put("INSTALLING", INSTALLING);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static EdgeStatusEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of EdgeStatusEnum values to list of string values.
     * @param toConvert The list of EdgeStatusEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<EdgeStatusEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (EdgeStatusEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 