/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.example.www.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * This is a model class for EncryptionKeyInformation type.
 */
public class EncryptionKeyInformation {
    private String id;
    private UUID companyId;
    private String key;
    private KeyAlgorithmEnum keyAlgorithm;
    private LocalDateTime lastBackupDate;

    /**
     * Default constructor.
     */
    public EncryptionKeyInformation() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  companyId  UUID value for companyId.
     * @param  key  String value for key.
     * @param  keyAlgorithm  KeyAlgorithmEnum value for keyAlgorithm.
     * @param  lastBackupDate  LocalDateTime value for lastBackupDate.
     */
    public EncryptionKeyInformation(
            String id,
            UUID companyId,
            String key,
            KeyAlgorithmEnum keyAlgorithm,
            LocalDateTime lastBackupDate) {
        this.id = id;
        this.companyId = companyId;
        this.key = key;
        this.keyAlgorithm = keyAlgorithm;
        this.lastBackupDate = lastBackupDate;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for CompanyId.
     * @return Returns the UUID
     */
    @JsonGetter("companyId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getCompanyId() {
        return companyId;
    }

    /**
     * Setter for CompanyId.
     * @param companyId Value for UUID
     */
    @JsonSetter("companyId")
    public void setCompanyId(UUID companyId) {
        this.companyId = companyId;
    }

    /**
     * Getter for Key.
     * @return Returns the String
     */
    @JsonGetter("key")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getKey() {
        return key;
    }

    /**
     * Setter for Key.
     * @param key Value for String
     */
    @JsonSetter("key")
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for KeyAlgorithm.
     * @return Returns the KeyAlgorithmEnum
     */
    @JsonGetter("keyAlgorithm")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public KeyAlgorithmEnum getKeyAlgorithm() {
        return keyAlgorithm;
    }

    /**
     * Setter for KeyAlgorithm.
     * @param keyAlgorithm Value for KeyAlgorithmEnum
     */
    @JsonSetter("keyAlgorithm")
    public void setKeyAlgorithm(KeyAlgorithmEnum keyAlgorithm) {
        this.keyAlgorithm = keyAlgorithm;
    }

    /**
     * Getter for LastBackupDate.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("lastBackupDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getLastBackupDate() {
        return lastBackupDate;
    }

    /**
     * Setter for LastBackupDate.
     * @param lastBackupDate Value for LocalDateTime
     */
    @JsonSetter("lastBackupDate")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setLastBackupDate(LocalDateTime lastBackupDate) {
        this.lastBackupDate = lastBackupDate;
    }

    /**
     * Converts this EncryptionKeyInformation into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EncryptionKeyInformation [" + "id=" + id + ", companyId=" + companyId + ", key="
                + key + ", keyAlgorithm=" + keyAlgorithm + ", lastBackupDate=" + lastBackupDate
                + "]";
    }

    /**
     * Builds a new {@link EncryptionKeyInformation.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EncryptionKeyInformation.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .companyId(getCompanyId())
                .key(getKey())
                .keyAlgorithm(getKeyAlgorithm())
                .lastBackupDate(getLastBackupDate());
        return builder;
    }

    /**
     * Class to build instances of {@link EncryptionKeyInformation}.
     */
    public static class Builder {
        private String id;
        private UUID companyId;
        private String key;
        private KeyAlgorithmEnum keyAlgorithm;
        private LocalDateTime lastBackupDate;



        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for companyId.
         * @param  companyId  UUID value for companyId.
         * @return Builder
         */
        public Builder companyId(UUID companyId) {
            this.companyId = companyId;
            return this;
        }

        /**
         * Setter for key.
         * @param  key  String value for key.
         * @return Builder
         */
        public Builder key(String key) {
            this.key = key;
            return this;
        }

        /**
         * Setter for keyAlgorithm.
         * @param  keyAlgorithm  KeyAlgorithmEnum value for keyAlgorithm.
         * @return Builder
         */
        public Builder keyAlgorithm(KeyAlgorithmEnum keyAlgorithm) {
            this.keyAlgorithm = keyAlgorithm;
            return this;
        }

        /**
         * Setter for lastBackupDate.
         * @param  lastBackupDate  LocalDateTime value for lastBackupDate.
         * @return Builder
         */
        public Builder lastBackupDate(LocalDateTime lastBackupDate) {
            this.lastBackupDate = lastBackupDate;
            return this;
        }

        /**
         * Builds a new {@link EncryptionKeyInformation} object using the set fields.
         * @return {@link EncryptionKeyInformation}
         */
        public EncryptionKeyInformation build() {
            return new EncryptionKeyInformation(id, companyId, key, keyAlgorithm, lastBackupDate);
        }
    }
}
