/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * KeyAlgorithmEnum to be used.
 */
public enum KeyAlgorithmEnum {
    RSA,

    ED25519;


    private static TreeMap<String, KeyAlgorithmEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        RSA.value = "RSA";
        ED25519.value = "ED25519";

        valueMap.put("RSA", RSA);
        valueMap.put("ED25519", ED25519);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static KeyAlgorithmEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of KeyAlgorithmEnum values to list of string values.
     * @param toConvert The list of KeyAlgorithmEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<KeyAlgorithmEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (KeyAlgorithmEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 