/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.example.www.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * This is a model class for PairingCodeInformation type.
 */
public class PairingCodeInformation {
    private UUID id;
    private UUID companyId;
    private List<ProductEntitlementEnum> productEntitlements;
    private UUID environmentId;
    private String pairingCode;
    private Integer reuseCount;
    private LocalDateTime expirationDate;
    private LocalDateTime modificationDate;

    /**
     * Default constructor.
     */
    public PairingCodeInformation() {
    }

    /**
     * Initialization constructor.
     * @param  id  UUID value for id.
     * @param  companyId  UUID value for companyId.
     * @param  productEntitlements  List of ProductEntitlementEnum value for productEntitlements.
     * @param  environmentId  UUID value for environmentId.
     * @param  pairingCode  String value for pairingCode.
     * @param  reuseCount  Integer value for reuseCount.
     * @param  expirationDate  LocalDateTime value for expirationDate.
     * @param  modificationDate  LocalDateTime value for modificationDate.
     */
    public PairingCodeInformation(
            UUID id,
            UUID companyId,
            List<ProductEntitlementEnum> productEntitlements,
            UUID environmentId,
            String pairingCode,
            Integer reuseCount,
            LocalDateTime expirationDate,
            LocalDateTime modificationDate) {
        this.id = id;
        this.companyId = companyId;
        this.productEntitlements = productEntitlements;
        this.environmentId = environmentId;
        this.pairingCode = pairingCode;
        this.reuseCount = reuseCount;
        this.expirationDate = expirationDate;
        this.modificationDate = modificationDate;
    }

    /**
     * Getter for Id.
     * @return Returns the UUID
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for UUID
     */
    @JsonSetter("id")
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for CompanyId.
     * @return Returns the UUID
     */
    @JsonGetter("companyId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getCompanyId() {
        return companyId;
    }

    /**
     * Setter for CompanyId.
     * @param companyId Value for UUID
     */
    @JsonSetter("companyId")
    public void setCompanyId(UUID companyId) {
        this.companyId = companyId;
    }

    /**
     * Getter for ProductEntitlements.
     * @return Returns the List of ProductEntitlementEnum
     */
    @JsonGetter("productEntitlements")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ProductEntitlementEnum> getProductEntitlements() {
        return productEntitlements;
    }

    /**
     * Setter for ProductEntitlements.
     * @param productEntitlements Value for List of ProductEntitlementEnum
     */
    @JsonSetter("productEntitlements")
    public void setProductEntitlements(List<ProductEntitlementEnum> productEntitlements) {
        this.productEntitlements = productEntitlements;
    }

    /**
     * Getter for EnvironmentId.
     * @return Returns the UUID
     */
    @JsonGetter("environmentId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getEnvironmentId() {
        return environmentId;
    }

    /**
     * Setter for EnvironmentId.
     * @param environmentId Value for UUID
     */
    @JsonSetter("environmentId")
    public void setEnvironmentId(UUID environmentId) {
        this.environmentId = environmentId;
    }

    /**
     * Getter for PairingCode.
     * @return Returns the String
     */
    @JsonGetter("pairingCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPairingCode() {
        return pairingCode;
    }

    /**
     * Setter for PairingCode.
     * @param pairingCode Value for String
     */
    @JsonSetter("pairingCode")
    public void setPairingCode(String pairingCode) {
        this.pairingCode = pairingCode;
    }

    /**
     * Getter for ReuseCount.
     * @return Returns the Integer
     */
    @JsonGetter("reuseCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getReuseCount() {
        return reuseCount;
    }

    /**
     * Setter for ReuseCount.
     * @param reuseCount Value for Integer
     */
    @JsonSetter("reuseCount")
    public void setReuseCount(Integer reuseCount) {
        this.reuseCount = reuseCount;
    }

    /**
     * Getter for ExpirationDate.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("expirationDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getExpirationDate() {
        return expirationDate;
    }

    /**
     * Setter for ExpirationDate.
     * @param expirationDate Value for LocalDateTime
     */
    @JsonSetter("expirationDate")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setExpirationDate(LocalDateTime expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * Getter for ModificationDate.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("modificationDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getModificationDate() {
        return modificationDate;
    }

    /**
     * Setter for ModificationDate.
     * @param modificationDate Value for LocalDateTime
     */
    @JsonSetter("modificationDate")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setModificationDate(LocalDateTime modificationDate) {
        this.modificationDate = modificationDate;
    }

    /**
     * Converts this PairingCodeInformation into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PairingCodeInformation [" + "id=" + id + ", companyId=" + companyId
                + ", productEntitlements=" + productEntitlements + ", environmentId="
                + environmentId + ", pairingCode=" + pairingCode + ", reuseCount=" + reuseCount
                + ", expirationDate=" + expirationDate + ", modificationDate=" + modificationDate
                + "]";
    }

    /**
     * Builds a new {@link PairingCodeInformation.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PairingCodeInformation.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .companyId(getCompanyId())
                .productEntitlements(getProductEntitlements())
                .environmentId(getEnvironmentId())
                .pairingCode(getPairingCode())
                .reuseCount(getReuseCount())
                .expirationDate(getExpirationDate())
                .modificationDate(getModificationDate());
        return builder;
    }

    /**
     * Class to build instances of {@link PairingCodeInformation}.
     */
    public static class Builder {
        private UUID id;
        private UUID companyId;
        private List<ProductEntitlementEnum> productEntitlements;
        private UUID environmentId;
        private String pairingCode;
        private Integer reuseCount;
        private LocalDateTime expirationDate;
        private LocalDateTime modificationDate;



        /**
         * Setter for id.
         * @param  id  UUID value for id.
         * @return Builder
         */
        public Builder id(UUID id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for companyId.
         * @param  companyId  UUID value for companyId.
         * @return Builder
         */
        public Builder companyId(UUID companyId) {
            this.companyId = companyId;
            return this;
        }

        /**
         * Setter for productEntitlements.
         * @param  productEntitlements  List of ProductEntitlementEnum value for
         *         productEntitlements.
         * @return Builder
         */
        public Builder productEntitlements(List<ProductEntitlementEnum> productEntitlements) {
            this.productEntitlements = productEntitlements;
            return this;
        }

        /**
         * Setter for environmentId.
         * @param  environmentId  UUID value for environmentId.
         * @return Builder
         */
        public Builder environmentId(UUID environmentId) {
            this.environmentId = environmentId;
            return this;
        }

        /**
         * Setter for pairingCode.
         * @param  pairingCode  String value for pairingCode.
         * @return Builder
         */
        public Builder pairingCode(String pairingCode) {
            this.pairingCode = pairingCode;
            return this;
        }

        /**
         * Setter for reuseCount.
         * @param  reuseCount  Integer value for reuseCount.
         * @return Builder
         */
        public Builder reuseCount(Integer reuseCount) {
            this.reuseCount = reuseCount;
            return this;
        }

        /**
         * Setter for expirationDate.
         * @param  expirationDate  LocalDateTime value for expirationDate.
         * @return Builder
         */
        public Builder expirationDate(LocalDateTime expirationDate) {
            this.expirationDate = expirationDate;
            return this;
        }

        /**
         * Setter for modificationDate.
         * @param  modificationDate  LocalDateTime value for modificationDate.
         * @return Builder
         */
        public Builder modificationDate(LocalDateTime modificationDate) {
            this.modificationDate = modificationDate;
            return this;
        }

        /**
         * Builds a new {@link PairingCodeInformation} object using the set fields.
         * @return {@link PairingCodeInformation}
         */
        public PairingCodeInformation build() {
            return new PairingCodeInformation(id, companyId, productEntitlements, environmentId,
                    pairingCode, reuseCount, expirationDate, modificationDate);
        }
    }
}
