/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for PairingCodeResponse type.
 */
public class PairingCodeResponse {
    private List<PairingCodeInformation> pairingCodes;

    /**
     * Default constructor.
     */
    public PairingCodeResponse() {
    }

    /**
     * Initialization constructor.
     * @param  pairingCodes  List of PairingCodeInformation value for pairingCodes.
     */
    public PairingCodeResponse(
            List<PairingCodeInformation> pairingCodes) {
        this.pairingCodes = pairingCodes;
    }

    /**
     * Getter for PairingCodes.
     * @return Returns the List of PairingCodeInformation
     */
    @JsonGetter("pairingCodes")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<PairingCodeInformation> getPairingCodes() {
        return pairingCodes;
    }

    /**
     * Setter for PairingCodes.
     * @param pairingCodes Value for List of PairingCodeInformation
     */
    @JsonSetter("pairingCodes")
    public void setPairingCodes(List<PairingCodeInformation> pairingCodes) {
        this.pairingCodes = pairingCodes;
    }

    /**
     * Converts this PairingCodeResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PairingCodeResponse [" + "pairingCodes=" + pairingCodes + "]";
    }

    /**
     * Builds a new {@link PairingCodeResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PairingCodeResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .pairingCodes(getPairingCodes());
        return builder;
    }

    /**
     * Class to build instances of {@link PairingCodeResponse}.
     */
    public static class Builder {
        private List<PairingCodeInformation> pairingCodes;



        /**
         * Setter for pairingCodes.
         * @param  pairingCodes  List of PairingCodeInformation value for pairingCodes.
         * @return Builder
         */
        public Builder pairingCodes(List<PairingCodeInformation> pairingCodes) {
            this.pairingCodes = pairingCodes;
            return this;
        }

        /**
         * Builds a new {@link PairingCodeResponse} object using the set fields.
         * @return {@link PairingCodeResponse}
         */
        public PairingCodeResponse build() {
            return new PairingCodeResponse(pairingCodes);
        }
    }
}
