/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.example.www.DateTimeHelper;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * This is a model class for PairingCodeRequest type.
 */
public class PairingCodeRequest {
    private UUID environmentId;
    private Integer reuseCount;
    private LocalDateTime expirationDate;

    /**
     * Default constructor.
     */
    public PairingCodeRequest() {
    }

    /**
     * Initialization constructor.
     * @param  environmentId  UUID value for environmentId.
     * @param  expirationDate  LocalDateTime value for expirationDate.
     * @param  reuseCount  Integer value for reuseCount.
     */
    public PairingCodeRequest(
            UUID environmentId,
            LocalDateTime expirationDate,
            Integer reuseCount) {
        this.environmentId = environmentId;
        this.reuseCount = reuseCount;
        this.expirationDate = expirationDate;
    }

    /**
     * Getter for EnvironmentId.
     * @return Returns the UUID
     */
    @JsonGetter("environmentId")
    public UUID getEnvironmentId() {
        return environmentId;
    }

    /**
     * Setter for EnvironmentId.
     * @param environmentId Value for UUID
     */
    @JsonSetter("environmentId")
    public void setEnvironmentId(UUID environmentId) {
        this.environmentId = environmentId;
    }

    /**
     * Getter for ReuseCount.
     * @return Returns the Integer
     */
    @JsonGetter("reuseCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getReuseCount() {
        return reuseCount;
    }

    /**
     * Setter for ReuseCount.
     * @param reuseCount Value for Integer
     */
    @JsonSetter("reuseCount")
    public void setReuseCount(Integer reuseCount) {
        this.reuseCount = reuseCount;
    }

    /**
     * Getter for ExpirationDate.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("expirationDate")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getExpirationDate() {
        return expirationDate;
    }

    /**
     * Setter for ExpirationDate.
     * @param expirationDate Value for LocalDateTime
     */
    @JsonSetter("expirationDate")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setExpirationDate(LocalDateTime expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * Converts this PairingCodeRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PairingCodeRequest [" + "environmentId=" + environmentId + ", expirationDate="
                + expirationDate + ", reuseCount=" + reuseCount + "]";
    }

    /**
     * Builds a new {@link PairingCodeRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PairingCodeRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(environmentId, expirationDate)
                .reuseCount(getReuseCount());
        return builder;
    }

    /**
     * Class to build instances of {@link PairingCodeRequest}.
     */
    public static class Builder {
        private UUID environmentId;
        private LocalDateTime expirationDate;
        private Integer reuseCount;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  environmentId  UUID value for environmentId.
         * @param  expirationDate  LocalDateTime value for expirationDate.
         */
        public Builder(UUID environmentId, LocalDateTime expirationDate) {
            this.environmentId = environmentId;
            this.expirationDate = expirationDate;
        }

        /**
         * Setter for environmentId.
         * @param  environmentId  UUID value for environmentId.
         * @return Builder
         */
        public Builder environmentId(UUID environmentId) {
            this.environmentId = environmentId;
            return this;
        }

        /**
         * Setter for expirationDate.
         * @param  expirationDate  LocalDateTime value for expirationDate.
         * @return Builder
         */
        public Builder expirationDate(LocalDateTime expirationDate) {
            this.expirationDate = expirationDate;
            return this;
        }

        /**
         * Setter for reuseCount.
         * @param  reuseCount  Integer value for reuseCount.
         * @return Builder
         */
        public Builder reuseCount(Integer reuseCount) {
            this.reuseCount = reuseCount;
            return this;
        }

        /**
         * Builds a new {@link PairingCodeRequest} object using the set fields.
         * @return {@link PairingCodeRequest}
         */
        public PairingCodeRequest build() {
            return new PairingCodeRequest(environmentId, expirationDate, reuseCount);
        }
    }
}
