/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PodStatusDetails type.
 */
public class PodStatusDetails {
    private String name;
    private Long age;
    private Integer restartCount;
    private String status;
    private Integer cpuUsage;
    private Long memoryUsage;

    /**
     * Default constructor.
     */
    public PodStatusDetails() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  age  Long value for age.
     * @param  restartCount  Integer value for restartCount.
     * @param  status  String value for status.
     * @param  cpuUsage  Integer value for cpuUsage.
     * @param  memoryUsage  Long value for memoryUsage.
     */
    public PodStatusDetails(
            String name,
            Long age,
            Integer restartCount,
            String status,
            Integer cpuUsage,
            Long memoryUsage) {
        this.name = name;
        this.age = age;
        this.restartCount = restartCount;
        this.status = status;
        this.cpuUsage = cpuUsage;
        this.memoryUsage = memoryUsage;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Age.
     * @return Returns the Long
     */
    @JsonGetter("age")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Long getAge() {
        return age;
    }

    /**
     * Setter for Age.
     * @param age Value for Long
     */
    @JsonSetter("age")
    public void setAge(Long age) {
        this.age = age;
    }

    /**
     * Getter for RestartCount.
     * @return Returns the Integer
     */
    @JsonGetter("restartCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getRestartCount() {
        return restartCount;
    }

    /**
     * Setter for RestartCount.
     * @param restartCount Value for Integer
     */
    @JsonSetter("restartCount")
    public void setRestartCount(Integer restartCount) {
        this.restartCount = restartCount;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for CpuUsage.
     * @return Returns the Integer
     */
    @JsonGetter("cpuUsage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCpuUsage() {
        return cpuUsage;
    }

    /**
     * Setter for CpuUsage.
     * @param cpuUsage Value for Integer
     */
    @JsonSetter("cpuUsage")
    public void setCpuUsage(Integer cpuUsage) {
        this.cpuUsage = cpuUsage;
    }

    /**
     * Getter for MemoryUsage.
     * @return Returns the Long
     */
    @JsonGetter("memoryUsage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Long getMemoryUsage() {
        return memoryUsage;
    }

    /**
     * Setter for MemoryUsage.
     * @param memoryUsage Value for Long
     */
    @JsonSetter("memoryUsage")
    public void setMemoryUsage(Long memoryUsage) {
        this.memoryUsage = memoryUsage;
    }

    /**
     * Converts this PodStatusDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PodStatusDetails [" + "name=" + name + ", age=" + age + ", restartCount="
                + restartCount + ", status=" + status + ", cpuUsage=" + cpuUsage + ", memoryUsage="
                + memoryUsage + "]";
    }

    /**
     * Builds a new {@link PodStatusDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PodStatusDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .name(getName())
                .age(getAge())
                .restartCount(getRestartCount())
                .status(getStatus())
                .cpuUsage(getCpuUsage())
                .memoryUsage(getMemoryUsage());
        return builder;
    }

    /**
     * Class to build instances of {@link PodStatusDetails}.
     */
    public static class Builder {
        private String name;
        private Long age;
        private Integer restartCount;
        private String status;
        private Integer cpuUsage;
        private Long memoryUsage;



        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for age.
         * @param  age  Long value for age.
         * @return Builder
         */
        public Builder age(Long age) {
            this.age = age;
            return this;
        }

        /**
         * Setter for restartCount.
         * @param  restartCount  Integer value for restartCount.
         * @return Builder
         */
        public Builder restartCount(Integer restartCount) {
            this.restartCount = restartCount;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for cpuUsage.
         * @param  cpuUsage  Integer value for cpuUsage.
         * @return Builder
         */
        public Builder cpuUsage(Integer cpuUsage) {
            this.cpuUsage = cpuUsage;
            return this;
        }

        /**
         * Setter for memoryUsage.
         * @param  memoryUsage  Long value for memoryUsage.
         * @return Builder
         */
        public Builder memoryUsage(Long memoryUsage) {
            this.memoryUsage = memoryUsage;
            return this;
        }

        /**
         * Builds a new {@link PodStatusDetails} object using the set fields.
         * @return {@link PodStatusDetails}
         */
        public PodStatusDetails build() {
            return new PodStatusDetails(name, age, restartCount, status, cpuUsage, memoryUsage);
        }
    }
}
