/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * ProductEntitlementEnum to be used.
 */
public enum ProductEntitlementEnum {
    ANY,

    MIRA,

    DEVOPS,

    OUTAGE_DETECTION;


    private static TreeMap<String, ProductEntitlementEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ANY.value = "ANY";
        MIRA.value = "MIRA";
        DEVOPS.value = "DEVOPS";
        OUTAGE_DETECTION.value = "OUTAGE_DETECTION";

        valueMap.put("ANY", ANY);
        valueMap.put("MIRA", MIRA);
        valueMap.put("DEVOPS", DEVOPS);
        valueMap.put("OUTAGE_DETECTION", OUTAGE_DETECTION);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static ProductEntitlementEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ProductEntitlementEnum values to list of string values.
     * @param toConvert The list of ProductEntitlementEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ProductEntitlementEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ProductEntitlementEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 