/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * StatusEnum to be used.
 */
public enum StatusEnum {
    DRAFT,

    PAIRED,

    ACTIVE,

    FAILED,

    INACTIVE;


    private static TreeMap<String, StatusEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        DRAFT.value = "DRAFT";
        PAIRED.value = "PAIRED";
        ACTIVE.value = "ACTIVE";
        FAILED.value = "FAILED";
        INACTIVE.value = "INACTIVE";

        valueMap.put("DRAFT", DRAFT);
        valueMap.put("PAIRED", PAIRED);
        valueMap.put("ACTIVE", ACTIVE);
        valueMap.put("FAILED", FAILED);
        valueMap.put("INACTIVE", INACTIVE);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static StatusEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of StatusEnum values to list of string values.
     * @param toConvert The list of StatusEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<StatusEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (StatusEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 