/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for WorkerServiceStatusDetails type.
 */
public class WorkerServiceStatusDetails {
    private String name;
    private String status;

    /**
     * Default constructor.
     */
    public WorkerServiceStatusDetails() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  status  String value for status.
     */
    public WorkerServiceStatusDetails(
            String name,
            String status) {
        this.name = name;
        this.status = status;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Converts this WorkerServiceStatusDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "WorkerServiceStatusDetails [" + "name=" + name + ", status=" + status + "]";
    }

    /**
     * Builds a new {@link WorkerServiceStatusDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link WorkerServiceStatusDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .name(getName())
                .status(getStatus());
        return builder;
    }

    /**
     * Class to build instances of {@link WorkerServiceStatusDetails}.
     */
    public static class Builder {
        private String name;
        private String status;



        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Builds a new {@link WorkerServiceStatusDetails} object using the set fields.
         * @return {@link WorkerServiceStatusDetails}
         */
        public WorkerServiceStatusDetails build() {
            return new WorkerServiceStatusDetails(name, status);
        }
    }
}
