/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.controllers;

import com.example.www.Environment;
import com.example.www.VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient;
import com.example.www.testing.HttpCallbackCatcher;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.rules.Timeout;

/**
 * Base class for all test cases.
 */
public class BaseControllerTest {
    /**
     * Test configuration.
     */
    public static final int REQUEST_TIMEOUT = 30;

    public static final double ASSERT_PRECISION = 0.01;
    
    /**
     * Global rules for tests.
     */
    @Rule
    public Timeout globalTimeout = Timeout.seconds(REQUEST_TIMEOUT);
    
    /**
     * Test fixtures,
     * Used to serve as HttpCallback and to capture request & response.
     */

    protected static HttpCallbackCatcher httpResponse;
    
    /**
     * Setup test.
     */
    @BeforeClass
    public static void setUp() throws Exception {
        httpResponse = new HttpCallbackCatcher(); 
    }

    /**
     * Tear down test.
     */
    @AfterClass
    public static void tearDown() throws Exception {
        httpResponse = null;
    }

    /**
     * Create test configuration from Environment variables.
     */
    protected static VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient createConfigurationFromEnvironment() {
        VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient.Builder builder =
                new VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient.Builder();

        final String environment =
                System.getenv("VENAFI_AS_A_SERVICE_API_FOR_EDGE_MANAGEMENT_SERVICE_OPERATIONS_LIB_ENVIRONMENT");
        final String defaultHost =
                System.getenv("VENAFI_AS_A_SERVICE_API_FOR_EDGE_MANAGEMENT_SERVICE_OPERATIONS_LIB_DEFAULT_HOST");
        final String timeout =
                System.getenv("VENAFI_AS_A_SERVICE_API_FOR_EDGE_MANAGEMENT_SERVICE_OPERATIONS_LIB_TIMEOUT");
        final String tpplApiKey =
                System.getenv("VENAFI_AS_A_SERVICE_API_FOR_EDGE_MANAGEMENT_SERVICE_OPERATIONS_LIB_TPPL_API_KEY");

        if (tpplApiKey != null) {
            builder.customHeaderAuthenticationCredentials(tpplApiKey);
        }
        if (environment != null) {
            builder.environment(Environment.fromString(environment));
        }
        if (defaultHost != null) {
            builder.defaultHost(defaultHost);
        }
        if (timeout != null) {
            builder.httpClientConfig(configBuilder -> configBuilder.timeout(
                    Long.parseLong(timeout)));
        }
        return builder.build();
    }

    
    /**
     * Create test configuration.
     */
    protected static VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient createConfiguration() {
        // Set Configuration parameters for test execution
        VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient config =
                createConfigurationFromEnvironment();
        config = config.newBuilder()
                .httpCallback(httpResponse)
                .build();
        return config;
    }
}
