/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import com.example.www.ApiHelper;
import com.example.www.VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient;
import com.example.www.exceptions.ApiException;
import com.example.www.models.PairingCodeRequest;
import com.example.www.testing.TestHelper;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class EdgeHubControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient client;
    
    /**
     * Controller instance (for all tests).
     */
    private static EdgeHubController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getEdgeHubController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * Retrieve list of all pairing codes used by edge instances for company.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestPairingcodesGetAll() throws Exception {

        // Set callback and perform API call
        try {
            controller.pairingcodesGetAll();
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

    }

    /**
     * Generate new pairing code for edge instance registration.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestPairingcodesCreate() throws Exception {
        // Parameters for the API call
        PairingCodeRequest body = null;

        // Set callback and perform API call
        try {
            controller.pairingcodesCreate(body);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 201", 
                201, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

    }

    /**
     * Retrieve list of all edge instances for company.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestEdgeinstancesGetAll() throws Exception {
        // Parameters for the API call
        UUID environmentId = null;

        // Set callback and perform API call
        try {
            controller.edgeinstancesGetAll(environmentId);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

    }

    /**
     * Retrieve the list of edge encryption keys based on query parameters.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestEdgeencryptionkeysGetAll() throws Exception {
        // Parameters for the API call
        UUID edgeInstanceId = null;

        // Set callback and perform API call
        try {
            controller.edgeencryptionkeysGetAll(edgeInstanceId);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

    }

    /**
     * Retrieve list of latest bills of materials.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestBillofmaterialsGetLatest() throws Exception {

        // Set callback and perform API call
        try {
            controller.billofmaterialsGetLatest();
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

    }

}
