/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www;

import com.example.www.controllers.EdgeHubController;
import com.example.www.controllers.EdgeWorkerController;
import com.example.www.http.client.HttpCallback;
import com.example.www.http.client.HttpClient;
import com.example.www.http.client.HttpClientConfiguration;
import com.example.www.http.client.OkClient;
import com.example.www.http.client.ReadonlyHttpClientConfiguration;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;

/**
 * Gateway class for the library.
 * This class acts as a factory for Controllers.
 * It holds the state of the SDK.
 */
public final class VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient implements Configuration {

    /**
     * Private store for controllers.
     */
    private EdgeHubController edgeHub;
    private EdgeWorkerController edgeWorker;

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * defaultHost value.
     */
    private final String defaultHost;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * CustomHeaderAuthenticationManager.
     */
    private CustomHeaderAuthenticationManager customHeaderAuthenticationManager;

    /**
     * Map of authentication Managers.
     */
    private Map<String, AuthManager> authManagers;

    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient(Environment environment,
            String defaultHost, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig, String tpplApiKey,
            Map<String, AuthManager> authManagers, HttpCallback httpCallback) {
        this.environment = environment;
        this.defaultHost = defaultHost;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.httpCallback = httpCallback;

        this.authManagers = (authManagers == null) ? new HashMap<>() : new HashMap<>(authManagers);
        if (this.authManagers.containsKey("global")) {
            this.customHeaderAuthenticationManager =
                    (CustomHeaderAuthenticationManager) this.authManagers.get("global");
        }

        if (!this.authManagers.containsKey("global")
                || !getCustomHeaderAuthenticationCredentials().equals(tpplApiKey)) {
            this.customHeaderAuthenticationManager = new CustomHeaderAuthenticationManager(
                    tpplApiKey);
            this.authManagers.put("global", customHeaderAuthenticationManager);
        }

        edgeHub = new EdgeHubController(this, this.httpClient, this.authManagers,
                this.httpCallback);
        edgeWorker = new EdgeWorkerController(this, this.httpClient, this.authManagers,
                this.httpCallback);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of EdgeHubController.
     * @return edgeHub
     */
    public EdgeHubController getEdgeHubController() {
        return edgeHub;
    }

    /**
     * Get the instance of EdgeWorkerController.
     * @return edgeWorker
     */
    public EdgeWorkerController getEdgeWorkerController() {
        return edgeWorker;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * defaultHost value.
     * @return defaultHost
     */
    public String getDefaultHost() {
        return defaultHost;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * The credentials to use with CustomHeaderAuthentication.
     * @return customHeaderAuthenticationCredentials
     */
    public CustomHeaderAuthenticationCredentials getCustomHeaderAuthenticationCredentials() {
        return customHeaderAuthenticationManager;
    }

    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        Map<String, SimpleEntry<Object, Boolean>> parameters = new HashMap<>();
        parameters.put("defaultHost",
                new SimpleEntry<Object, Boolean>(this.defaultHost, false));
        StringBuilder baseUrl = new StringBuilder(environmentMapper(environment, server));
        ApiHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.ENUM_DEFAULT);
    }

    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://{defaultHost}";
            }
        }
        return "https://{defaultHost}";
    }

    /**
     * Converts this VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient [" + "environment="
                + environment + ", defaultHost=" + defaultHost + ", httpClientConfig="
                + httpClientConfig + ", authManagers=" + authManagers + "]";
    }

    /**
     * Builds a new {@link VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.defaultHost = getDefaultHost();
        builder.httpClient = getHttpClient();
        builder.tpplApiKey = getCustomHeaderAuthenticationCredentials().getTpplApiKey();
        builder.authManagers = authManagers;
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(configBldr -> configBldr =
                ((HttpClientConfiguration) httpClientConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private String defaultHost = "www.example.com";
        private HttpClient httpClient;
        private String tpplApiKey = "";
        private Map<String, AuthManager> authManagers = null;
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();


        /**
         * Credentials setter for CustomHeaderAuthentication.
         * @param tpplApiKey String value for tpplApiKey.
         * @return Builder
         */
        public Builder customHeaderAuthenticationCredentials(String tpplApiKey) {
            if (tpplApiKey == null) {
                throw new NullPointerException("TpplApiKey cannot be null.");
            }
            this.tpplApiKey = tpplApiKey;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * defaultHost value.
         * @param defaultHost The defaultHost for client.
         * @return Builder
         */
        public Builder defaultHost(String defaultHost) {
            this.defaultHost = defaultHost;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Builds a new VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient object using the set fields.
         * @return VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient
         */
        public VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            httpClient = new OkClient(httpClientConfig);

            return new VenafiAsAServiceAPIForEdgeManagementServiceOperationsClient(environment,
                    defaultHost, httpClient, httpClientConfig, tpplApiKey, authManagers,
                    httpCallback);
        }
    }
}