/*
 * VenafiAsAServiceAPIForEdgeManagementServiceOperationsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.exceptions;

import com.example.www.http.client.HttpContext;
import com.example.www.models.ErrorInformation;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for ErrorResponseException type.
 */
public class ErrorResponseException
        extends ApiException {
    private static final long serialVersionUID = 108367180063788638L;
    private List<ErrorInformation> errors;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public ErrorResponseException(String reason, HttpContext context) {
        super(reason, context);
    }


    /**
     * Getter for Errors.
     * @return Returns the List of ErrorInformation
     */
    @JsonGetter("errors")
    public List<ErrorInformation> getErrors() {
        return this.errors;
    }

    /**
     * Setter for Errors.
     * @param errors Value for List of ErrorInformation
     */
    @JsonSetter("errors")
    private void setErrors(List<ErrorInformation> errors) {
        this.errors = errors;
    }
}
